### ISSUE TITLE
More easy to implement

### ISSUE THREAD

**Issue by EmpiezaAProgramar** [edubarr/header-decor#21]
I have tried to implement your library, but adapters and recyclerview are very complex in my project and when I tried to add new code from your example it is really hard.

Maybe you should try to do something like this project: https://github.com/carlonzo/StikkyHeader just call one method and you get the header.

Thank you for your work.

**Comment by edubarr** [comment]
Your opinion is certainly valid and you are free to contribute any changes you want to make this easier to use. :+1:
