### ISSUE TITLE
Header item's child click event

### ISSUE THREAD

**Issue by riontech-xten** [edubarr/header-decor#33]
header item's child click is not working

here is my code
`public HeaderViewHolder(View itemView) {
            super(itemView);
            this.textView = (TextView) itemView.findViewById(R.id.txtDateSection);
            itemView.findViewById(R.id.imgClickTest).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Toast.makeText(context, "Position=>"+ getAdapterPosition(), Toast.LENGTH_LONG).show();
                }
            });
        }`

**Comment by edubarr** [comment]
You have to check for click events by implementing `RecyclerView.OnItemTouchListener`. This was already discussed on issue #26 so please refer to that thread for the information you need.
