### ISSUE TITLE
Can we make a  view - Linear or Relative sticky?

### ISSUE THREAD

**Issue by AnandKhinvasara** [edubarr/header-decor#37]
So What when I use the library it seems that we can only make the textViews stick because it doesnt accept any other views. Am I doing something wrong or is the library designed that way?

**Comment by edubarr** [comment]
You have total control over what to use as a view in the sticky headers. You inflate your own layout in a class that implements the `StickyHeaderAdapter` interface. It works exactly the same as a `RecyclerView.Adapter` with a `ViewHolder` to hold the header's view references.

**Comment by starkej2** [comment]
The library supports that functionality. Please provide more details if you are still having issues with your implementation @AnandKhinvasara.
