### ISSUE TITLE
protected  hasHeader(int position)

### ISSUE THREAD

**Issue by MarcusWolschon** [edubarr/header-decor#39]
private boolean StickyHeaderDecoration::hasHeader(int position)
should be protected,

so subclasses can define specific items (such as empty-views, special items or footers) to have no header.

**Comment by edubarr** [comment]
@MarcusWolschon I didn't think too much about that when first coding the decoration but it sounds like the correct approach to take. Would you feel comfortable creating a pull request with those changes? I can take care of if it not.

**Comment by starkej2** [comment]
This behavior can now be accomplished by returning `StickyHeaderDecoration.NO_HEADER_ID` from the `StickyHeaderAdapter.getHeaderId(position)` method for items that you don't want to have a header.

**Comment by starkej2** [comment]
Resolved in #48
