### ISSUE TITLE
How about double header with render inline?

### ISSUE THREAD

**Issue by viettanbkdn** [edubarr/header-decor#42]
It will be useful

**Comment by RuiEEE** [comment]
Is it possible to achieve this? I've been messing around with the subheader height but the offsets gets messed up.

**Comment by edubarr** [comment]
I'm fairly certain it is possible, you just need to put certain constraints in place. For example, the header is not inlined, just the sub-header so only the header height counts towards the y-axis offset. Unfortunately I don't have the time to look into it at this moment, but maybe in a couple weeks. If you manage to get it working and feel like contributing, PRs are always welcome. :)

**Comment by RuiEEE** [comment]
Yesterday I grabbed this updated lib to get it working, and noticed that I was using version 0.2.6, turns out version 0.2.7 already had this functionality, passing true as second parameter of DoubleHeaderDecoration.

I guess you can close this.
