### ISSUE TITLE
Can't scroll to bottom

### ISSUE THREAD

**Issue by dmitrikudrenko** [edubarr/header-decor#52]
In my application I have the list of countries phone's codes. And I need to open that list with shown selected item. But when the selected item is last recyclerview can't scroll to the end.
![screenshot_2016-10-14-09-28-55](https://cloud.githubusercontent.com/assets/3238570/19380869/313bebe6-920a-11e6-802e-9a5d6689fb7d.png)
![screenshot_2016-10-14-09-29-01](https://cloud.githubusercontent.com/assets/3238570/19380873/332c284e-920a-11e6-92a8-89f74f29d4b9.png)

**Comment by edubarr** [comment]
@dmitrikudrenko form the image I can see you're using the sitcky header decoration on both views. It has worked correctly with selection for me and I can't reproduce this issue. Could you provide sample code that reproduces this behaviour? Thanks!

**Comment by dmitrikudrenko** [comment]
I updated recyclerview support library version and the problem has been disappeared
