### ISSUE TITLE
Sample code to How to use.

### ISSUE THREAD

**Issue by Naresh-Katta** [edubarr/header-decor#53]
Hi there,
I'm new to android, I just wanted to use the app in my upcoming project. Please give us wiki link or sample code to how to use the library in code like in [Sticky Headers Recyclerview](https://github.com/timehop/sticky-headers-recyclerview).

**Comment by edubarr** [comment]
@Naresh-Katta You'll find all the information you need on the sample project. There are examples on how to use each type of sticky header there.

**Comment by hafsalrahman** [comment]
The sample doesn't show how to pass data and headers to the adapter how it will it fetch from collections we passed
