### ISSUE TITLE
header can't really hidden in version 0.2.8

### ISSUE THREAD

**Issue by shuimuqinghua** [edubarr/header-decor#54]
when i use v0.2.8 and when i scrolling the recyclerview, the header of  which item will attach the top is showing,  the word(A,B,C,D...) will changing still. 
but when i change to v0.2.6, this problem disappeared。

**Comment by starkej2** [comment]
I don't quite understand the issue you're describing. Can you provide a screenshot and/or some sample code to help debug the problem?
