### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by akrupych-remit** [edubarr/header-decor#58]
I'm getting error trying to build my project with header-decor dependency:

- Information:Gradle tasks [:app:assembleDebug]
- Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
- > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

Here's my dependencies from app-level build.gradle:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'ca.barrenechea.header-decor:header-decor:0.2.8'
}

**Comment by shubham-kumar2001** [comment]
Finished with error: Gradle task assembleDebug failed with exit code -1
I'm getting this error

**Comment by heathenthrone48** [comment]
Exception: Gradle task assembleDebug failed with exit code -1

im getting this error , cannot find any resources in the internet. really weird

**Comment by ravikant16** [comment]
Launching lib\main.dart on A37f in debug mode...
Running Gradle task 'assembleDebug'...
Exception: Gradle task assembleDebug failed with exit code -1
what is the solution
