### ISSUE TITLE
Support different header view types

### ISSUE THREAD

**Issue by grandstaish** [edubarr/header-decor#65]
You'll need to do is deprecate `onCreateHeaderViewHolder(ViewGroup parent)` and add a new method: `onCreateHeaderViewHolder(ViewGroup parent, int viewType)`

The viewType can be derived from the adapter like so: 

```
mAdapter.getItemViewType(position);
```

This makes it consistent with the `onCreateViewHolder(ViewGroup parent, int viewType)` method.

(As a side note, you should really add nullability annotations. Nice implementation otherwise!)

**Comment by starkej2** [comment]
Resolved in #83
