### ISSUE TITLE
Is it possible to disable sticking?

### ISSUE THREAD

**Issue by ivametal** [edubarr/header-decor#79]
Is it possible to disable sticking???

**Comment by ivametal** [comment]
Solved.

I add 1 line in a lib code :)

**Comment by nareshkatta99** [comment]
in 
```
getHeaderTop(@NonNull RecyclerView parent, @NonNull View child,
            @NonNull View header, int adapterPos, int layoutPos)
```
method there is a line `top = Math.max(0, top)`
This is the one line you have to change I suppose.
