### ISSUE TITLE
Two first headers are not show

### ISSUE THREAD

**Issue by jstr14** [edubarr/header-decor#81]
Hello,

It's the first time with this library and I have one problem at show headers. I implement an Adapter with SkickyHeaderAdapter,  I do that my adapter add one sticky header for every item of my list, but the two first headers aren't visible, instead there are a big empty space on every one. The other headers works propertly.

I don't know what is happening. Any one can help me please?

Thank you.

**Comment by starkej2** [comment]
Make sure you're returning a value >= 0 in your `StickyHeaderAdapter.getHeaderId` implementatino for those first two items.
