### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by starkej2** [edubarr/header-decor#93]
Continuous integration would be helpful to make sure proposed pull requests build successfully. [CircleCi](https://circleci.com) would be pretty easy to set up, but I'm not an admin in the repo so maybe @edubarr can help.

**Comment by edubarr** [comment]
I added the circleci webhook now all we need is the config file and it should be all setup.

**Comment by starkej2** [comment]
Nice! thanks @edubarr
